apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: zb-api
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zb-api
  labels:
    app: zb-api
spec:
  selector:
    matchLabels:
      app: zb-api
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: zb-api
      name: zb-api
    spec:
      containers:
        - name: zb-api
          image: asia.gcr.io/goquo-activities/zouba-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: zb-api-config
            - secretRef:
                name: zb-secrets
          env:
            - name: GAE_SERVICE
              value: k8s-api
            - name: IS_EVENT_HANDLER
              value: 'false'
            - name: APP_LOG_NAME
              value: zb-api
          livenessProbe:
            httpGet:
              path: /v1/config
              port: 8080
          readinessProbe:
            httpGet:
              path: /v1/config
              port: 8080      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zb-jobs
  labels:
    app: zb-jobs
spec:
  selector:
    matchLabels:
      app: zb-jobs
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: zb-jobs
      name: zb-jobs
    spec:
      containers:
        - name: zb-jobs
          image: asia.gcr.io/goquo-activities/zouba-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: zb-api-config
            - secretRef:
                name: zb-secrets
          env:
            - name: GAE_SERVICE
              value: k8s-jobs
            - name: IS_EVENT_HANDLER
              value: 'true'
            - name: APP_LOG_NAME
              value: zb-jobs
            - name: AXIOS_DEBUG
              value: 'false'
          livenessProbe:
            httpGet:
              path: /VERSION.txt
              port: 8080
          readinessProbe:
            httpGet:
              path: /v1/config
              port: 8080