apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: gdg-app
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdg-app
  labels:
    app: gdg-app
spec:
  selector:
    matchLabels:
      app: gdg-app
  template:
    metadata:
      labels:
        app: gdg-app
      name: gdg-app
    spec:
      containers:
        - name: gdg-app
          image: asia.gcr.io/gdgkl-demo-tim/gdgdemo-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: app-secrets