apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: gdg-nginx
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdg-nginx
  labels:
    app: gdg-nginx
spec:
  selector:
    matchLabels:
      app: gdg-nginx
  template:
    metadata:
      labels:
        app: gdg-nginx
      name: gdg-nginx
    spec:
      containers:
        - name: gdg-nginx
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-proxy-conf
              mountPath: /etc/nginx/conf.d/app.conf
              subPath: app.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-proxy-conf
          configMap:
            name: nginx-proxy-conf