bases:
  - ../../base
generatorOptions:
  annotations:
    kustomize.generated.resource: 'true'
namePrefix: prod-

patchesStrategicMerge:
- resource-usage/nginx.yml
resources:
- templates/certs.yml
- templates/ingress.yml
- templates/cdn-backendconfig.yml
configMapGenerator:
- name: nginx-proxy-conf
  files:
  - configmap-files/app.conf
secretGenerator:
- name: app-secrets
  files:
  - secrets/secrets.env