apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cdn-backendconfig
spec:
  cdn:
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
    enabled: true
